### ISSUE TITLE
Module 2 - Group Capstone Project

### ISSUE THREAD

**Issue by JuanDiegoGuerra** [JuanDiegoGuerra/Module_2-Capstone#21]
### Group capstone: set up your Kanban board
[JD - Lincoln / Group Capstone Project](https://github.com/JuanDiegoGuerra/Module_2-Capstone/projects/1)

- For this capstone our team is made up of 2 people, so we are deleting everying related to "Student C" since we don't have a 3rd partner.
  - 15 "cards/issues" will ramain after deleting "Student C tasks".

**Comment by ghost** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go ahead with your project




## Highlights

✅ Tasks are descriptive


## Required Changes ♻️

- [ ] Your task cards are not assigned to anyone. After assigning, your cards should look like the image below

![image](https://github.com/JuanDiegoGuerra/Module_2-Capstone/assets/98453979/25b17ef5-af87-45ca-a1d3-c3cc39acf667)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by JuanDiegoGuerra** [comment]
REQURED CHANGES MADE 🛠 
- We have updated the assigments for:
  - Student A: @JuanDiegoGuerra 
  - Student B: @lincoln1883

**Comment by addod19** [comment]
### Hi @frank1738 and @lincoln1883, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [ ] Nice job making some of the changes :rocket: 


 ## Required Changes ♻️
_Check the comments under the review._
- [ ] One of the card(Add header) is not assigned a member as we can see in the screenshot below
![Screenshot from 2023-05-22 19-34-20](https://github.com/JuanDiegoGuerra/Module_2-Capstone/assets/46388113/7016f618-d302-4d25-b679-74d29880397f)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lincoln1883** [comment]
REQUIRED CHANGES MADE 🛠 
- We have updated the assignments for:
  - Task#17 which was missing an assignee.

**Comment by levy002** [comment]
## Hello @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
